Add a guide to rendering 3D Tiles with Cesium Native.
CesiumGS/cesium-native pull request #1022
Opened 2024-12-04 09:30 UTC by kring

Fixes #982 

Also added a topic for #981 but it's just a placeholder for now.

2024-12-09 18:53 UTC, azrogers commented
Looks good to me! Only one minor typo to fix.

2024-12-12 02:14 UTC, azrogers requested changes

2024-12-12 02:32 UTC, kring commented
Thanks @azrogers, I fixed the typo.

2024-12-13 15:27 UTC, merged

2024-12-13 15:27 UTC, azrogers commented
Thanks for the guide @kring!