Fixed build warning - I3dmToGltfConverter.cpp:634:14: error: ‘positio…
CesiumGS/cesium-native pull request #910
Opened 2024-06-19 10:06 UTC by Ulvesson

Found a compiler warning that might be problematic. See
I3dmToGltfConverter.cpp:634:14: error: ‘position.glm::vec<3, double, glm::packed_highp>::x’ may be used uninitialized [-Werror=maybe-uninitialized]

copyInstanceToBuffer might return data based on uninitialized variables.

Fixed by adding a check and an error message. The error message might not be good enough but the compiler is happy.

2024-06-20 00:31 UTC, kring commented
Thanks for the PR @Ulvesson! Before we can review and merge this, can I please bug you to sign our Contributor License Agreement?
https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla

2024-06-20 04:25 UTC, Ulvesson commented
I have signed the CLA now.

2024-06-20 10:18 UTC, timoore commented
This looks good to me. decompose() can return without setting the result variables... which shouldn't happen, but you never know.

2024-06-20 10:46 UTC, kring requested changes
Looks good @Ulvesson, and thanks again for the PR! I just have one requested change, if you don't mind.

2024-06-20 14:23 UTC, Ulvesson commented
I am not 100% sure about the default values but I think I have fixed the code as requested.

2024-06-25 10:58 UTC, kring commented
Thanks again for the PR @Ulvesson!

2024-06-25 11:04 UTC, merged