Add a test for raster overlay upsampled bounding volumes, and fix a bug with upsampling and gltfUpAxis
CesiumGS/cesium-native pull request #919
Opened 2024-06-29 00:27 UTC by kring

This is a follow on to #917 that adds a test for one of the bug fixes in that PR:

> Fixed a bug while upsampling tiles for raster overlays that could cause them to have an incorrect bounding box, which in some cases would lead to the raster overlay being missing entirely from the upsampled tile.

However, in the course of writing this test, I found an unrelated bug where raster overlay upsampling was not correctly accounting for the non-standard but relatively widely used `gltfUpAxis` property. So this PR fixes that as well.

2024-06-30 09:47 UTC, kring commented
I'm tempted to merge this myself to include in tomorrow's release, since it's a useful fix and low risk. But I'll move it out of the release instead so that it can have a proper review.

2024-07-26 13:58 UTC, j9liu requested changes
@kring looks like there's a failing test across CI (the same one): 

```
The following tests FAILED:
	 72 - Test the tileset content manager's post processing for gltf (SEGFAULT)
```

When I run the tests locally, I'm getting an error out here: 

![image](https://github.com/user-attachments/assets/b9c6e728-4dab-487f-877e-0ed8860a00fc)
![image](https://github.com/user-attachments/assets/167efa73-5d12-45e7-9a95-e81970a7f8ae)

Do you mind fixing this? Once it's fixed I'm happy to merge :smile:

2024-07-26 13:58 UTC, j9liu commented on Cesium3DTilesSelection/test/TestTilesetContentManager.cpp
> +        "Generate raster overlay details when tile don't have loose region") {
```suggestion
        "Generate raster overlay details when tile doesn't have loose region") {
```

2024-07-26 17:19 UTC, j9liu commented
Thanks @kring! Merging now.

2024-07-26 17:19 UTC, merged