Add getFeatureIdAccessorView for instances
CesiumGS/cesium-native pull request #934
Opened 2024-08-05 09:20 UTC by timoore

Implement getFeatureIdAccessorView for feature IDs stored in the EXT_mesh_gpu_instancing extension. Refactor the existing function, used for accessing feature IDs in primitives, to use common code.

2024-08-12 14:57 UTC, j9liu requested changes
Thanks @timoore! This looks good code-wise, but do you mind doing two things before we merge?

- [ ] Update CHANGES.md
- [ ] Add unit tests

2024-08-12 14:57 UTC, j9liu commented on CesiumGltf/src/AccessorUtility.cpp
> +  // restriction.
Nitpick, but do you mind moving this comment underneath the `case Accessor::ComponentType::UNSIGNED_INT` ?

2024-08-15 19:29 UTC, timoore commented
@j9liu this awaits your approval!

2024-08-19 11:51 UTC, timoore commented
@j9liu thanks for the Changelog entry; ! forgot!

2024-08-19 14:24 UTC, j9liu commented
No worries @timoore ! I also wanted to add one more unit test to catch an invalid case, then I'll merge. Will do that in a bit

2024-08-19 18:47 UTC, merged